import "../styles/reset.scss";
import "../styles/geral.scss";

export const metadata = {
  title: "Global Solution 2023",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  );
}
