
import "../styles/reset.scss";
import "../styles/geral.scss";
import Footer from "../Components/Footer";
import Nav from "../Components/Nav";



export const metadata = {
  title: "Global Solution 2023",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Nav/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
